cargo-features = ["edition2024"]

[package]
name = "crowsa"
version = "3.0.0"
description = "A lightweight alternative to Tauri."
authors = ["Jaydon Nelson <xxdr@duck.com>"]
license = "MIT"
readme = "README.md"
repository = "https://codeberg.org/pparaxan/Crowsa"
edition = "2024"
keywords = [ "web", "gui", "desktop" ]
categories = [ "gui", "web-programming" ]

[dependencies]
hyaline = { path = "hyaline/" }

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "cazic"
path = "examples/cazic.rs"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
