cargo-features = ["edition2024"]

[package]
name = "crowsa"
version = "0.0.1"
description = "A lightweight alternative to Tauri."
authors = ["Jaydon \"xan\" Nelson <xxdr@duck.com>"]
license = "MIT"
readme = "README.md"
repository = "https://codeberg.org/xxan/Crowsa"
edition = "2024"
keywords = [ "web", "gui", "desktop" ]
categories = [ "gui", "web-programming" ]

[dependencies]
hyaline = { path = "webview" }

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
