# format:
#
# package
# dependencies
# features
# profiles
# examples

[package]
name = "quark"
version = "3.0.0"
description = "A lightweight alternative to Electron."
authors = ["Jaydon Nelson <xxdr@duck.com>"]
license = "MIT"
readme = "README.md"
repository = "https://codeberg.org/pparaxan/Quark"
edition = "2021"
keywords = [ "web", "gui", "desktop" ]
categories = [ "gui", "web-programming" ]

[dependencies]
include_dir = "0.7.4"
tiny_http = "0.12.0"

[build-dependencies]
cc = "1.2.1"

[target.'cfg(any(target_os = "linux", target_family = "bsd"))'.build-dependencies]
pkg-config = "0.3.31"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true

[[example]]
name = "helloworld"
path = "examples/helloworld.rs"
