cargo-features = ["edition2024"]

[package]
name = "quark"
version = "3.0.0"
description = "A lightweight alternative to Electron."
authors = ["Jaydon Nelson <xxdr@duck.com>"]
license = "MIT"
readme = "README.md"
repository = "https://codeberg.org/pparaxan/Quark"
edition = "2024"
keywords = [ "web", "gui", "desktop" ]
categories = [ "gui", "web-programming" ]

[dependencies]
hyaline = { path = "hyaline/" }
include_dir = "0.7.4"

[[example]]
name = "helloworld"
path = "examples/helloworld.rs"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
