name: testing

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  tests:
    runs-on: self-hosted
    container:
      image: 'rustlang/rust:nightly'
    steps:
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt install nodejs
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Report versions
        run: |
          rustc --version
          cargo --version
          cargo pkgid
          node -v
          npm -v
      - name: Run tests on Crowsa
        run: cargo test -v
