---
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    runs-on: self-hosted
    container:
      image: "rustlang/rust:nightly"
    steps:
      - name: Install dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_23.x | bash -
          apt install nodejs libwebkit2gtk-4.1-dev weston -y
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Report versions
        run: |
          rustc --version
          cargo --version
          cargo pkgid
          echo "node $(node -v)"
          echo "npm $(npm -v)"
      - name: Start headless interface
        run: |
          echo $XDG_RUNTIME_DIR
          weston --no-config --socket=wl-test-env --backend=headless
          echo "weston should be all set, continuing..."
      - name: Run tests on Quark
        run: env WAYLAND_DISPLAY=wl-test-env cargo test --test main -v
